spring:
  datasource:
    # IMPORTANTE: Permitimos que Docker inyecte la URL, o usamos localhost por defecto
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/devdb}
    username: ${DB_USERNAME:ups}
    password: ${DB_PASSWORD:ups123}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

server:
  port: 8080

# Corregida la sangría de management (debe estar al mismo nivel que 'spring')
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      # Cambia 'always' por 'never' para evitar el error 500 por exceso de detalles
      show-details: never